version: '3.8'

services:
  tilik-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tilik_ai_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - PORT=8000
      - HOST=0.0.0.0
